### ISSUE TITLE
Multi threaded fishtape

### ISSUE THREAD

**Issue by pickfire** [fisherman/fishtape#17]
I notice that fishtape will not run tests in parallel, will this be solved in the future?

https://github.com/sstephenson/bats/issues/143

**Comment by bucaran** [comment]
The way things are implemented is that `setup` and `teardown` run each once for every test, making writing unit tests easy, but _feature_ test a bit more complicated due to its atomic nature. On the other hand, this strict design also means that tests are isolated from other tests.

As for the interleaved output, it does not matter what tests are done first as long as they write `ok` or `not ok` to standard output and do not interfere with other files.

I don't know if this feature is possible, but I will give it a shot when I get more time.

**Comment by pickfire** [comment]
@bucaran Most of the time they do not interfere, we should probably add some method to stop multi-threading for some files if it will interfere. Well, I think it is a really minor case.

**Comment by bucaran** [comment]
How do we handle the following scenario:

```
function setup
    printf "%s\n" hello bye > file
end

function teardown
    rm file
end

test "check file"
    (sed -n 1p file) = "hello"
end

test "check file"
    (sed -n 2p file) = "bye"
end
```

**Comment by pickfire** [comment]
Probably put the first test file in between the teardown function? And use functions as break?

**Comment by bucaran** [comment]
That's not possible right now. The code I posted above is run like this:

```
setup
test_check_file_1
teardown
setup
test_check_file_2
end
```

**Comment by jbucaran** [comment]
Don't really think so.
